"""
FreshGuard AI - Synthetic Grocery Dataset Loader & Generator
"""

import json
from pathlib import Path
from typing import List, Dict, Any

SYNTHETIC_GROCERY_DATA: List[Dict[str, Any]] = [
    {
        "id": "DT-MILK-01",
        "sku": "SKU-MILK-01",
        "name": "Fresh Whole Milk (1 Gallon)",
        "category": "Dairy",
        "store": "Downtown Market",
        "current_stock": 42,
        "history_sales": [16, 18, 15, 20, 22, 25, 19],
        "unit_price": 4.29,
        "unit_cost": 2.50,
        "days_to_expiry": 2,
        "lead_time_days": 2,
        "incoming_shipment": 0,
        "shelf_life_total": 10,
        "storage_type": "Chilled",
        "historical_waste_units": 14,
    },
    {
        "id": "SH-MILK-01",
        "sku": "SKU-MILK-01",
        "name": "Fresh Whole Milk (1 Gallon)",
        "category": "Dairy",
        "store": "Suburban Hub",
        "current_stock": 8,
        "history_sales": [24, 28, 22, 26, 30, 35, 27],
        "unit_price": 4.29,
        "unit_cost": 2.50,
        "days_to_expiry": 6,
        "lead_time_days": 2,
        "incoming_shipment": 0,
        "shelf_life_total": 10,
        "storage_type": "Chilled",
        "historical_waste_units": 6,
    },
    {
        "id": "DT-BREAD-02",
        "sku": "SKU-BREAD-02",
        "name": "Artisan Whole Wheat Bread (Loaf)",
        "category": "Bakery",
        "store": "Downtown Market",
        "current_stock": 35,
        "history_sales": [10, 12, 11, 14, 15, 18, 12],
        "unit_price": 3.89,
        "unit_cost": 1.60,
        "days_to_expiry": 1,
        "lead_time_days": 1,
        "incoming_shipment": 0,
        "shelf_life_total": 5,
        "storage_type": "Ambient",
        "historical_waste_units": 20,
    },
    {
        "id": "SH-BREAD-02",
        "sku": "SKU-BREAD-02",
        "name": "Artisan Whole Wheat Bread (Loaf)",
        "category": "Bakery",
        "store": "Suburban Hub",
        "current_stock": 18,
        "history_sales": [15, 14, 16, 18, 20, 22, 17],
        "unit_price": 3.89,
        "unit_cost": 1.60,
        "days_to_expiry": 4,
        "lead_time_days": 1,
        "incoming_shipment": 15,
        "shelf_life_total": 5,
        "storage_type": "Ambient",
        "historical_waste_units": 8,
    },
    {
        "id": "DT-BANANA-03",
        "sku": "SKU-BANANA-03",
        "name": "Cavendish Bananas (Bunch)",
        "category": "Produce",
        "store": "Downtown Market",
        "current_stock": 60,
        "history_sales": [25, 28, 30, 26, 32, 35, 29],
        "unit_price": 1.99,
        "unit_cost": 0.85,
        "days_to_expiry": 2,
        "lead_time_days": 2,
        "incoming_shipment": 0,
        "shelf_life_total": 6,
        "storage_type": "Ambient",
        "historical_waste_units": 35,
    },
    {
        "id": "SH-BANANA-03",
        "sku": "SKU-BANANA-03",
        "name": "Cavendish Bananas (Bunch)",
        "category": "Produce",
        "store": "Suburban Hub",
        "current_stock": 5,
        "history_sales": [35, 40, 38, 42, 45, 50, 41],
        "unit_price": 1.99,
        "unit_cost": 0.85,
        "days_to_expiry": 3,
        "lead_time_days": 2,
        "incoming_shipment": 0,
        "shelf_life_total": 6,
        "storage_type": "Ambient",
        "historical_waste_units": 15,
    },
    {
        "id": "DT-TOMATO-04",
        "sku": "SKU-TOMATO-04",
        "name": "Organic Vine Tomatoes (1 kg)",
        "category": "Produce",
        "store": "Downtown Market",
        "current_stock": 28,
        "history_sales": [8, 9, 7, 10, 11, 13, 9],
        "unit_price": 4.49,
        "unit_cost": 2.10,
        "days_to_expiry": 3,
        "lead_time_days": 2,
        "incoming_shipment": 0,
        "shelf_life_total": 7,
        "storage_type": "Produce Cooler",
        "historical_waste_units": 12,
    },
    {
        "id": "SH-TOMATO-04",
        "sku": "SKU-TOMATO-04",
        "name": "Organic Vine Tomatoes (1 kg)",
        "category": "Produce",
        "store": "Suburban Hub",
        "current_stock": 22,
        "history_sales": [14, 16, 15, 18, 19, 21, 16],
        "unit_price": 4.49,
        "unit_cost": 2.10,
        "days_to_expiry": 5,
        "lead_time_days": 2,
        "incoming_shipment": 20,
        "shelf_life_total": 7,
        "storage_type": "Produce Cooler",
        "historical_waste_units": 10,
    },
    {
        "id": "DT-YOGURT-05",
        "sku": "SKU-YOGURT-05",
        "name": "Greek Yogurt Vanilla (500g)",
        "category": "Dairy",
        "store": "Downtown Market",
        "current_stock": 50,
        "history_sales": [9, 11, 10, 8, 12, 14, 10],
        "unit_price": 4.99,
        "unit_cost": 2.70,
        "days_to_expiry": 3,
        "lead_time_days": 3,
        "incoming_shipment": 0,
        "shelf_life_total": 14,
        "storage_type": "Chilled",
        "historical_waste_units": 18,
    },
    {
        "id": "SH-YOGURT-05",
        "sku": "SKU-YOGURT-05",
        "name": "Greek Yogurt Vanilla (500g)",
        "category": "Dairy",
        "store": "Suburban Hub",
        "current_stock": 12,
        "history_sales": [18, 22, 20, 19, 25, 27, 21],
        "unit_price": 4.99,
        "unit_cost": 2.70,
        "days_to_expiry": 8,
        "lead_time_days": 3,
        "incoming_shipment": 0,
        "shelf_life_total": 14,
        "storage_type": "Chilled",
        "historical_waste_units": 7,
    },
    {
        "id": "DT-SPINACH-06",
        "sku": "SKU-SPINACH-06",
        "name": "Crisp Baby Spinach (300g)",
        "category": "Produce",
        "store": "Downtown Market",
        "current_stock": 32,
        "history_sales": [7, 8, 9, 6, 10, 11, 8],
        "unit_price": 3.49,
        "unit_cost": 1.40,
        "days_to_expiry": 2,
        "lead_time_days": 1,
        "incoming_shipment": 0,
        "shelf_life_total": 5,
        "storage_type": "Produce Cooler",
        "historical_waste_units": 24,
    },
    {
        "id": "SH-SPINACH-06",
        "sku": "SKU-SPINACH-06",
        "name": "Crisp Baby Spinach (300g)",
        "category": "Produce",
        "store": "Suburban Hub",
        "current_stock": 6,
        "history_sales": [12, 14, 15, 13, 17, 19, 14],
        "unit_price": 3.49,
        "unit_cost": 1.40,
        "days_to_expiry": 3,
        "lead_time_days": 1,
        "incoming_shipment": 0,
        "shelf_life_total": 5,
        "storage_type": "Produce Cooler",
        "historical_waste_units": 11,
    },
    {
        "id": "DT-BERRY-07",
        "sku": "SKU-BERRY-07",
        "name": "Fresh Strawberries (400g)",
        "category": "Produce",
        "store": "Downtown Market",
        "current_stock": 25,
        "history_sales": [12, 14, 11, 15, 16, 20, 13],
        "unit_price": 4.99,
        "unit_cost": 2.40,
        "days_to_expiry": 1,
        "lead_time_days": 2,
        "incoming_shipment": 0,
        "shelf_life_total": 4,
        "storage_type": "Produce Cooler",
        "historical_waste_units": 30,
    },
    {
        "id": "SH-BERRY-07",
        "sku": "SKU-BERRY-07",
        "name": "Fresh Strawberries (400g)",
        "category": "Produce",
        "store": "Suburban Hub",
        "current_stock": 4,
        "history_sales": [18, 20, 19, 22, 24, 28, 21],
        "unit_price": 4.99,
        "unit_cost": 2.40,
        "days_to_expiry": 2,
        "lead_time_days": 2,
        "incoming_shipment": 0,
        "shelf_life_total": 4,
        "storage_type": "Produce Cooler",
        "historical_waste_units": 16,
    },
    {
        "id": "DT-CHICKEN-08",
        "sku": "SKU-CHICKEN-08",
        "name": "Boneless Chicken Breast (500g)",
        "category": "Meat",
        "store": "Downtown Market",
        "current_stock": 19,
        "history_sales": [14, 15, 16, 13, 17, 21, 15],
        "unit_price": 6.99,
        "unit_cost": 4.10,
        "days_to_expiry": 2,
        "lead_time_days": 1,
        "incoming_shipment": 0,
        "shelf_life_total": 5,
        "storage_type": "Chilled",
        "historical_waste_units": 15,
    },
    {
        "id": "SH-CHICKEN-08",
        "sku": "SKU-CHICKEN-08",
        "name": "Boneless Chicken Breast (500g)",
        "category": "Meat",
        "store": "Suburban Hub",
        "current_stock": 45,
        "history_sales": [20, 22, 25, 21, 28, 30, 24],
        "unit_price": 6.99,
        "unit_cost": 4.10,
        "days_to_expiry": 4,
        "lead_time_days": 1,
        "incoming_shipment": 25,
        "shelf_life_total": 5,
        "storage_type": "Chilled",
        "historical_waste_units": 12,
    },
    {
        "id": "DT-CHEESE-09",
        "sku": "SKU-CHEESE-09",
        "name": "Mild Cheddar Cheese Block (400g)",
        "category": "Dairy",
        "store": "Downtown Market",
        "current_stock": 30,
        "history_sales": [6, 7, 5, 8, 9, 10, 7],
        "unit_price": 5.49,
        "unit_cost": 3.00,
        "days_to_expiry": 14,
        "lead_time_days": 4,
        "incoming_shipment": 0,
        "shelf_life_total": 30,
        "storage_type": "Chilled",
        "historical_waste_units": 3,
    },
    {
        "id": "SH-CHEESE-09",
        "sku": "SKU-CHEESE-09",
        "name": "Mild Cheddar Cheese Block (400g)",
        "category": "Dairy",
        "store": "Suburban Hub",
        "current_stock": 8,
        "history_sales": [10, 12, 11, 13, 15, 17, 12],
        "unit_price": 5.49,
        "unit_cost": 3.00,
        "days_to_expiry": 12,
        "lead_time_days": 4,
        "incoming_shipment": 0,
        "shelf_life_total": 30,
        "storage_type": "Chilled",
        "historical_waste_units": 2,
    },
    {
        "id": "DT-AVOCADO-10",
        "sku": "SKU-AVOCADO-10",
        "name": "Hass Avocados (Pack of 3)",
        "category": "Produce",
        "store": "Downtown Market",
        "current_stock": 24,
        "history_sales": [8, 10, 9, 11, 12, 15, 10],
        "unit_price": 3.99,
        "unit_cost": 1.80,
        "days_to_expiry": 2,
        "lead_time_days": 2,
        "incoming_shipment": 0,
        "shelf_life_total": 6,
        "storage_type": "Ambient",
        "historical_waste_units": 19,
    },
    {
        "id": "SH-AVOCADO-10",
        "sku": "SKU-AVOCADO-10",
        "name": "Hass Avocados (Pack of 3)",
        "category": "Produce",
        "store": "Suburban Hub",
        "current_stock": 28,
        "history_sales": [14, 16, 15, 17, 19, 22, 16],
        "unit_price": 3.99,
        "unit_cost": 1.80,
        "days_to_expiry": 4,
        "lead_time_days": 2,
        "incoming_shipment": 0,
        "shelf_life_total": 6,
        "storage_type": "Ambient",
        "historical_waste_units": 10,
    },
    {
        "id": "DT-PEPPERS-11",
        "sku": "SKU-PEPPERS-11",
        "name": "Bell Peppers Tri-Color (Pack of 3)",
        "category": "Produce",
        "store": "Downtown Market",
        "current_stock": 16,
        "history_sales": [5, 6, 7, 6, 8, 9, 6],
        "unit_price": 3.79,
        "unit_cost": 1.70,
        "days_to_expiry": 4,
        "lead_time_days": 2,
        "incoming_shipment": 15,
        "shelf_life_total": 8,
        "storage_type": "Produce Cooler",
        "historical_waste_units": 8,
    },
    {
        "id": "SH-PEPPERS-11",
        "sku": "SKU-PEPPERS-11",
        "name": "Bell Peppers Tri-Color (Pack of 3)",
        "category": "Produce",
        "store": "Suburban Hub",
        "current_stock": 7,
        "history_sales": [11, 13, 12, 14, 16, 18, 13],
        "unit_price": 3.79,
        "unit_cost": 1.70,
        "days_to_expiry": 3,
        "lead_time_days": 2,
        "incoming_shipment": 0,
        "shelf_life_total": 8,
        "storage_type": "Produce Cooler",
        "historical_waste_units": 7,
    },
    {
        "id": "DT-BAGEL-12",
        "sku": "SKU-BAGEL-12",
        "name": "Cinnamon Raisin Bagels (6pk)",
        "category": "Bakery",
        "store": "Downtown Market",
        "current_stock": 20,
        "history_sales": [6, 7, 8, 6, 9, 11, 7],
        "unit_price": 4.19,
        "unit_cost": 1.80,
        "days_to_expiry": 1,
        "lead_time_days": 1,
        "incoming_shipment": 0,
        "shelf_life_total": 5,
        "storage_type": "Ambient",
        "historical_waste_units": 16,
    },
    {
        "id": "SH-BAGEL-12",
        "sku": "SKU-BAGEL-12",
        "name": "Cinnamon Raisin Bagels (6pk)",
        "category": "Bakery",
        "store": "Suburban Hub",
        "current_stock": 14,
        "history_sales": [10, 12, 11, 13, 15, 17, 12],
        "unit_price": 4.19,
        "unit_cost": 1.80,
        "days_to_expiry": 3,
        "lead_time_days": 1,
        "incoming_shipment": 12,
        "shelf_life_total": 5,
        "storage_type": "Ambient",
        "historical_waste_units": 9,
    },
]

def load_grocery_data() -> List[Dict[str, Any]]:
    """Returns a deep-copy list of the synthetic grocery dataset."""
    json_path = Path(__file__).parent / "freshguard_data.json"
    if json_path.exists():
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return [dict(item) for item in SYNTHETIC_GROCERY_DATA]
